export interface AnamnesisDTO {
    id?: string,
    patientId: string,
    smoker: string,
    pregnant: string,
    headecha: string,
    insomnia: string,
    diabete: string,
    hypertension: string,
    stress: string,
    circulatory: string,
    allergy: string,
    anaemia: string,
    legPain: string,
    backPain: string,
    physical: string,
    physicalName: string,
    anotherDisease: string,
    surgery: string,
    surgeryName: string,
    medicament: string,
    medicamentName: string,
    reclamation: string ,
    phrase: string,
    project: string,
}
